language: bash
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y curl discount unzip python-pip
- sudo pip install mkdocs mkdocs-material
- wget -O /tmp/gmirror-2.2.2.tar.gz https://github.com/sinkcup/gmirror/archive/2.2.2.tar.gz
- tar -zxvf /tmp/gmirror-2.2.2.tar.gz -C /tmp/
- cp /tmp/gmirror-2.2.2/*.sh ./
install:
- bash ./portal.build.sh
script:
- test $TRAVIS_PULL_REQUEST == "false" && echo "travis-ci don't support qiniu, so deploy manually" || exit 0
- bash ./before_upload.sh
- export PATH=$PATH:$PWD/qiniu/
- bash ./portal.upload.sh
